template_path: remote/vpc.yaml
stack_name: archvpc
dependencies:
  - prod/bootstrap.yaml
parameters:
  VpcSubnetPrefix: "10.10"
  VpcName: archvpc
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
