template_path: templates/backup.yaml
stack_name: backup
dependencies:
  - essentials
parameters:
  EncryptBucket: 'true'
  BucketVersioning: 'Suspended'
  EnableGlacierLifeCycle: 'Disabled'
  GlacierTransition: '1'
  GlacierExpiration: '30'
