template_path: templates/backup.yaml
stack_name: backup
dependencies:
  - essentials
parameters:
  EncryptBucket: 'true'
  BucketVersioning: 'Suspended'
  EnableGlacierLifeCycle: 'Enabled'
  GlacierTransition: '1'
