template_path: templates/backup.yaml
stack_name: backup
dependencies:
  - essentials
parameters:
  EncryptBucket: "true"
  EnableVersioning: "Enabled"
  EnableGlacierLifeCycle: "Enabled"
  GlacierTransition: "1"
