sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - master
install:
  - pip install yamllint cfn-lint
  - pip install git+git://github.com/cloudreach/sceptre@v2.1.4
  - pip install git+git://github.com/zaro0508/sceptre-ssm-resolver.git
  - pip install git+git://github.com/zaro0508/sceptre-date-resolver.git
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: validate
      script:
        - yamllint ./config ./templates
        - cfn-lint ./templates/**/*
    - stage: deploy
      script:
        - export ACCOUNT="sandbox"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
    - stage: deploy
      script:
        - export ACCOUNT="burner"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
