language: python
python: 3.7
cache: pip
branches:
  only:
  - master
install:
  - pip install yamllint cfn-lint
  - pip install sceptre sceptre-ssm-resolver sceptre-date-resolver
stages:
  - name: validate
  - name: deploy
    if: branch = master AND type = push
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - yamllint ./config ./templates
        - cfn-lint ./templates/**/*
    - stage: deploy
      name: "organizations"
      script:
        - export ACCOUNT="organizations"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
    - stage: deploy
      name: "burner"
      script:
        - export ACCOUNT="burner"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
    - stage: deploy
      name: "sandbox"
      script:
        - export ACCOUNT="sandbox"
        - ./setup_aws_cli.sh $ACCOUNT || travis_terminate 1
        - sceptre launch $ACCOUNT --yes
