template_path: "jumpcloud-idp.yaml"
stack_name: "arch-sandbox-admin"
stack_tags:
  Project: "Infrastructure"
parameters:
  SamlProviderName: "arch-sandbox-admin"
  SamlProviderPolicyArns:
    - "arn:aws:iam::aws:policy/AdministratorAccess"
    - "arn:aws:iam::aws:policy/job-function/Billing"
  Metadata: !file_contents idp/jumpcloud/arch-sandbox-admin.xml
dependencies:
  - "sandbox/cfn-cr-saml-provider.yaml"
