AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Account Policies

Parameters:
  minimumPasswordLength:
    Type: Number
    Default: 8
    MinValue: 8
    MaxValue: 128

Resources:
  PasswordPolicy:
    Type: Community::IAM::PasswordPolicy
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3001
    Properties:
      MinimumPasswordLength: !Sub '${minimumPasswordLength}'
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      AllowUsersToChangePassword: false
