Description: Setup a backup bucket
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EncryptBucket:
    Type: String
    Description: true to encrypt bucket, false (default) for no encryption
    AllowedValues:
      - true
      - false
    Default: false
  EnableGlacierLifeCycle:
    Type: String
    Description: Enabled to enable Glacier lifecycle rule, default is Disabled
    AllowedValues:
      - Enabled
      - Disabled
    Default: Disabled
  GlacierTransition:
    Type: Number
    Description: Number of days until S3 objects are moved to Glacier
    Default: 7
  GlacierExpiration:
    Type: Number
    Description: Number of days (from creation) when objects are deleted from S3 and Glacier
    Default: 365000
Conditions:
  EnableEncryption: !Equals [!Ref EncryptBucket, true]
  DisableEncryption: !Not [!Condition EnableEncryption]
Resources:
  BackupBucket:
    Type: "AWS::S3::Bucket"
    Condition: DisableEncryption
    Properties:
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Status: !Ref EnableGlacierLifeCycle
          ExpirationInDays: !Ref GlacierExpiration
          Transitions:
            - TransitionInDays: !Ref GlacierTransition
              StorageClass: Glacier
  EncryptedBackupBucket:
    Type: "AWS::S3::Bucket"
    Condition: EnableEncryption
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Status: !Ref EnableGlacierLifeCycle
          ExpirationInDays: !Ref GlacierExpiration
          Transitions:
            - TransitionInDays: !Ref GlacierTransition
              StorageClass: Glacier
Outputs:
  BackupBucket:
    Condition: DisableEncryption
    Value: !Ref BackupBucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BackupBucket'
  EncryptedBackupBucket:
    Condition: EnableEncryption
    Value: !Ref EncryptedBackupBucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BackupBucket'
