AWSTemplateFormatVersion: '2010-09-09'
Description: 'create resources for org-formation'

Parameters:

  masterAccountId:
    Type: String

Resources:
  # Role for cross account access
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: OrganizationAccountAccessRole
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
         - Effect: Allow
           Action: sts:AssumeRole
           Principal:
            AWS: !Ref masterAccountId
