AWSTemplateFormatVersion: '2010-09-09-OC'
Description: org-formation template for archsolutions-organizations account

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: archsolutions-organizations
      Alias: archsolutions-organizations
      AccountId: '364599566324'
      RootEmail: arch.solutions.aws.organizations@gmail.com
      PasswordPolicy: !Ref PasswordPolicy
      Tags:
        budget-alarm-threshold: '100'
        account-owner-email: zaro0508@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref RestrictUnusedRegionsSCP

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development

  # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples.html#examples_general
  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - "a4b:*"
              - "acm:*"
              - "aws-marketplace-management:*"
              - "aws-marketplace:*"
              - "aws-portal:*"
              - "awsbillingconsole:*"
              - "budgets:*"
              - "ce:*"
              - "chime:*"
              - "cloudfront:*"
              - "config:*"
              - "cur:*"
              - "directconnect:*"
              - "ec2:DescribeRegions"
              - "ec2:DescribeTransitGateways"
              - "ec2:DescribeVpnGateways"
              - "fms:*"
              - "globalaccelerator:*"
              - "health:*"
              - "iam:*"
              - "importexport:*"
              - "kms:*"
              - "mobileanalytics:*"
              - "networkmanager:*"
              - "organizations:*"
              - "pricing:*"
              - "route53:*"
              - "route53domains:*"
              - "s3:GetAccountPublic*"
              - "s3:ListAllMyBuckets"
              - "s3:PutAccountPublic*"
              - "shield:*"
              - "sts:*"
              - "support:*"
              - "trustedadvisor:*"
              - "waf-regional:*"
              - "waf:*"
              - "wafv2:*"
              - "wellarchitected:*"
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - us-east-1

  PasswordPolicy:
    Type: OC::ORG::PasswordPolicy
    Properties:
      MaxPasswordAge: 720
      MinimumPasswordLength: 12
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      PasswordReusePrevention: 5
      AllowUsersToChangePassword: true
