AWSTemplateFormatVersion: '2010-09-09-OC'
Description: org-formation template for archsolutions-organizations account

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: archsolutions-organizations
      Alias: archsolutions-organizations
      AccountId: '364599566324'
      RootEmail: arch.solutions.aws.organizations@gmail.com
      PasswordPolicy: !Ref PasswordPolicy
      Tags:
        budget-alarm-threshold: '100'
        account-owner-email: zaro0508@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref RestrictUnusedRegionsSCP

  BurnerAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: arch.solutions.burner@gmail.com
      AccountName: org-archsolutions-burner
      AccountId: '430215734166'
      Alias: org-archsolutions-burner
      Tags:
        budget-alarm-threshold: '20'
        account-owner-email: zaro0508@gmail.com

  SandboxAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: arch-solutions-aws-sandbox@gmail.com
      AccountName: org-archsolutions-sandbox
      AccountId: '968106938717'
      Alias: org-archsolutions-sandbox
      Tags:
        budget-alarm-threshold: '20'
        account-owner-email: zaro0508@gmail.com

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref BurnerAccount
        - !Ref SandboxAccount

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - '*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - us-east-1

  PasswordPolicy:
    Type: OC::ORG::PasswordPolicy
    Properties:
      MaxPasswordAge: 720
      MinimumPasswordLength: 12
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      PasswordReusePrevention: 5
      AllowUsersToChangePassword: true
