AWSTemplateFormatVersion: '2010-09-09-OC'
Description: org-formation template for archsolutions-organizations account

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: org-archsolutions-organizations
      Alias: org-archsolutions-organizations
      AccountId: '364599566324'
      RootEmail: arch.solutions.aws.organizations@gmail.com
      Tags:
        budget-alarm-threshold: '100'
        account-owner-email: zaro0508@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref RestrictUnusedRegionsSCP

  Org-archsolutions-burnerAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: org-archsolutions-burner
      AccountId: '430215734166'
      RootEmail: arch.solutions.burner@gmail.com
      Alias: org-archsolutions-burner
      Tags:
        budget-alarm-threshold: '20'
        account-owner-email: zaro0508@gmail.com

  Org-archsolutions-sandboxAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: org-archsolutions-sandbox
      AccountId: '968106938717'
      RootEmail: arch.solutions.aws.sandbox@gmail.com
      Alias: org-archsolutions-sandbox
      Tags:
        budget-alarm-threshold: '20'
        account-owner-email: zaro0508@gmail.com

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref Org-archsolutions-burnerAccount
        - !Ref Org-archsolutions-sandboxAccount

  # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples.html#examples_general
  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'a4b:*'
              - 'acm:*'
              - 'aws-marketplace-management:*'
              - 'aws-marketplace:*'
              - 'aws-portal:*'
              - 'awsbillingconsole:*'
              - 'budgets:*'
              - 'ce:*'
              - 'chime:*'
              - 'cloudfront:*'
              - 'config:*'
              - 'cur:*'
              - 'directconnect:*'
              - 'ec2:DescribeRegions'
              - 'ec2:DescribeTransitGateways'
              - 'ec2:DescribeVpnGateways'
              - 'fms:*'
              - 'globalaccelerator:*'
              - 'health:*'
              - 'iam:*'
              - 'importexport:*'
              - 'kms:*'
              - 'mobileanalytics:*'
              - 'networkmanager:*'
              - 'organizations:*'
              - 'pricing:*'
              - 'route53:*'
              - 'route53domains:*'
              - 's3:GetAccountPublic*'
              - 's3:ListAllMyBuckets'
              - 's3:PutAccountPublic*'
              - 'shield:*'
              - 'sts:*'
              - 'support:*'
              - 'trustedadvisor:*'
              - 'waf-regional:*'
              - 'waf:*'
              - 'wafv2:*'
              - 'wellarchitected:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - us-east-1
